---
name: Lint (Golang)
on:  # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, synchronize]
    paths: ["src/api-proxy/**/*"]

jobs:
  golangci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3.5.0
        with:
          go-version: 1.19
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
      - uses: golangci/golangci-lint-action@0ad9a0988b3973e851ab0a07adf248ec2e100376 # v3.3.1
        with:
          version: latest
          working-directory: ./src/api-proxy

  codeql:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
      - uses: github/codeql-action/init@62b14cbbadf0c1d9d5ee2534d236a31c9bbd83ac  # tag=codeql-bundle-20221024
        with:
          languages: go
      - uses: github/codeql-action/autobuild@62b14cbbadf0c1d9d5ee2534d236a31c9bbd83ac  # tag=codeql-bundle-20221024
      - uses: github/codeql-action/analyze@62b14cbbadf0c1d9d5ee2534d236a31c9bbd83ac  # tag=codeql-bundle-20221024
