---
name: Security (Helm Charts)
on: # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, synchronize]
    paths: ["charts/**"]
  push:
    branches: [main]

jobs:
  check_helm_issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
      - uses: tenable/terrascan-action@dd7e921056c6f25b25bff3cf791e063ed7fc3a78 # tag=v1.5.0
        continue-on-error: true
        with:
          find_vulnerabilities: true
          iac_dir: charts
          iac_type: helm
          iac_version: v3
          sarif_upload: true
      - uses: github/codeql-action/upload-sarif@62b14cbbadf0c1d9d5ee2534d236a31c9bbd83ac # tag=codeql-bundle-20221024
        with:
          sarif_file: terrascan.sarif
